name: tii-microxrce-agent

on:
  push:
    branches: [ "riscv64" ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [fog-ros-baseimage-update]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_GIT_SHA=$calculatedSha" >> $GITHUB_OUTPUT

      - name: Set image tag format without suffix
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Set image tag format with suffix
        # it is possible that run_number should be used instead run_attempt
        # run_attempt is unique number on every run and run_attempt resets to 1 if re-build is not used
        # content of image_sha_tag_suffix is defined in fog-ros-baseimage dispatcher workflow.
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha,suffix=-${{ github.event.client_payload.image_sha_tag_suffix }}" >> $GITHUB_ENV
        if: github.event_name == 'repository_dispatch'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-microxrce-agent
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest
            ${{ env.IMAGE_TAG_FORMAT }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,riscv64,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        run: |
          TAG=${{ steps.vars.outputs.SHORT_GIT_SHA }} \
          docker buildx bake --provenance=false --push

      - name: Create manifest list
        run: |
          docker buildx imagetools create \
          -t ghcr.io/tiiuae/tii-microxrce-agent:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }} \
          ghcr.io/tiiuae/tii-microxrce-agent:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-amd64 \
          ghcr.io/tiiuae/tii-microxrce-agent:sha-${{ steps.vars.outputs.SHORT_GIT_SHA }}-riscv64